version: "3.9"
services:
  
    
  TektAIBack:
    container_name: tektai-back
    image: "tektai-back"
    build: .\TEKTAI-BACK
    ports:
      - "3000:3000"   
    environment:
      - MONGO_URL=mongodb://mongodb:27017/TektAI
    depends_on:
      - mongodb


  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    restart: unless-stopped  

  
  